name: Tosca CI/CD Demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  
  test:
    # The type of runner that the job will run on
    runs-on: self-hosted
    
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run automated tests
        run: C:\GitHub-Runner\tosca_execution_client.ps1 -toscaServerUrl "https://prdtos01.qbsa.local/" -events '["Aakash_Dex"]' -projectName "QBCC_Workspace" -resultsFileName "results.xml" -clientId "21489a0b-c163-4a62-b61e-501090c9506aMgAxADQAOAA5AGEAMABiAC0AYwAxADYAMwAtADQAYQA2ADIALQBiADYAMQBlAC0ANQAwADEAMAA5ADAAYwA5ADUAMAA2AGEAas/AmaXo8dBjGCZzwfsfnF0z8az7ptz9cukmcPbJMfOn+kE0HlhfXX6UNkJdMgKX" -clientSecret "21489a0b-c163-4a62-b61e-501090c9506aMgAxADQAOAA5AGEAMABiAC0AYwAxADYAMwAtADQAYQA2ADIALQBiADYAMQBlAC0ANQAwADEAMAA5ADAAYwA5ADUAMAA2AGEAR2g0XcYfnt/LynM1Sz8/u0zmOgblahN/eyl7SOeZu6RjiJS6SLZgCyzaRU6ule+NkQpLZ0b2E4+p5pkJ1btOiw+kkMu4RyZV2I1tpkw2GnIi3Jvn7pzO4usW6DOr+dK+"
        
   
  
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          report_paths: 'C:\\GitHub-Runners\\results\\results.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
